services:
#    product.fixtures:
#        class: App\DataFixtures\ProductFixtures
#        tags: ['doctrine.fixture.orm']
#        arguments:
#            - "@faker.generator"

    country.fixtures:
        class: App\DataFixtures\CountryFixtures
        tags: ['doctrine.fixture.orm']

    address.fixtures:
        class: App\DataFixtures\AddressFixtures
        tags: ['doctrine.fixture.orm']

    company.fixtures:
        class: App\DataFixtures\CompanyFixtures
        tags: ['doctrine.fixture.orm']

    file.fixtures:
        class: App\DataFixtures\FileFixtures
        tags: ['doctrine.fixture.orm']

    client.fixtures:
        class: App\DataFixtures\ClientFixtures
        tags: ['doctrine.fixture.orm']

    invoice.fixtures:
        class: App\DataFixtures\InvoiceFixtures
        tags: ['doctrine.fixture.orm']

    order.fixtures:
        class: App\DataFixtures\OrderFixtures
        tags: ['doctrine.fixture.orm']

    role.fixtures:
        class: App\DataFixtures\RoleFixtures
        tags: ['doctrine.fixture.orm']

    product.fixtures:
        class: App\DataFixtures\ProductFixtures
        tags: ['doctrine.fixture.orm']

    user.fixtures:
        class: App\DataFixtures\UserFixtures
        tags: ['doctrine.fixture.orm']
        arguments:
            - "@security.user_password_encoder.generic"

    text.fixtures:
        class: App\DataFixtures\TextFixtures
        tags: ['doctrine.fixture.orm']
